'use strict';
const fs = require('fs');
const path = require('path');

const CATEGORIES = ['topics', 'sessions', 'snapshots'];
const HEADER_COMMENT = '<!-- generated by tools/memory.js — do not edit by hand -->';

function readH1Title(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const m = content.match(/^# (.+?)\s*$/m);
  return m ? m[1] : null;
}

function readEntries(root) {
  const memoryDir = path.join(root, 'docs', 'memory');
  if (!fs.existsSync(memoryDir)) return [];
  const entries = [];
  for (const cat of CATEGORIES) {
    const dir = path.join(memoryDir, cat);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith('.md')) continue;
      const filePath = path.join(dir, f);
      const title = readH1Title(filePath) || f.replace(/\.md$/, '');
      const dateMatch = f.match(/^(\d{4}-\d{2}-\d{2})/);
      entries.push({
        category: cat,
        title,
        file: path.relative(root, filePath).replace(/\\/g, '/'),
        date: dateMatch ? dateMatch[1] : null,
      });
    }
  }
  return entries;
}

function renderIndex(entries) {
  const groups = { topics: [], sessions: [], snapshots: [] };
  for (const e of entries) {
    if (groups[e.category]) groups[e.category].push(e);
  }
  groups.topics.sort((a, b) => a.title.localeCompare(b.title));
  groups.sessions.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
  groups.snapshots.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

  const lines = [
    HEADER_COMMENT,
    '',
    '# MEMORY.md',
    '',
    'Persistent semantic knowledge base. Topic files in `docs/memory/`. Updated automatically by `generate-plan.js`.',
    '',
  ];

  const sectionHeading = { topics: 'Topics', sessions: 'Sessions', snapshots: 'Snapshots' };
  for (const cat of CATEGORIES) {
    const items = groups[cat];
    if (items.length === 0) continue;
    lines.push(`## ${sectionHeading[cat]}`, '');
    for (const e of items) {
      const dateSuffix = e.date ? ` · ${e.date}` : '';
      lines.push(`- [${e.title}](${e.file})${dateSuffix}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function compactMemory(opts) {
  const { root } = opts;
  const entries = readEntries(root);
  if (entries.length === 0) return;
  const text = renderIndex(entries);
  fs.writeFileSync(path.join(root, 'MEMORY.md'), text + '\n');
}

module.exports = { renderIndex, compactMemory, readEntries };
