// App shell — chrome with dashboard + theme toggles + About modal. Persists selection.

const { useEffect, useState, useCallback } = React;

function AboutModal({ dash, onClose }) {
  const D = window.DATA;
  const P = D.project;
  const T = D.tool;
  useEffect(() => {
    const onKey = (e) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className="about-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }} role="dialog" aria-modal="true" aria-labelledby="about-title">
      <div className="about-card">
        <button className="close" onClick={onClose} aria-label="Close">×</button>

        <div className="about-head">
          <span className="about-plate" aria-hidden="true">{P.name.slice(0,1)}</span>
          <div>
            <h2 id="about-title">{P.name}</h2>
            <p className="tag">{P.tagline}</p>
          </div>
          <span className={`mode-badge ${dash === "plan" ? "mode-report" : "mode-live"}`}>
            <span className="pip" />
            {dash === "plan" ? "REPORT" : "LIVE"}
          </span>
        </div>

        <div className="about-body">
          <section className="about-sec">
            <h4>This Project</h4>
            <dl className="about-kv">
              <dt>Name</dt><dd>{P.name}</dd>
              <dt>Version</dt><dd>v{P.version}</dd>
              <dt>Branch</dt><dd>{P.branch}</dd>
              <dt>Build</dt><dd>#{P.buildNumber} · {P.commitSha}</dd>
              <dt>Repo</dt><dd><a href={P.githubUrl} target="_blank" rel="noopener noreferrer">{P.githubUrl.replace(/^https?:\/\//, "")}</a></dd>
              <dt>Updated</dt><dd className="plain">{P.updated}</dd>
            </dl>

            <h4 style={{ marginTop: 18 }}>Dashboard Tool</h4>
            <dl className="about-kv">
              <dt>Generated by</dt><dd>{T.appName} v{T.version}</dd>
              <dt>Generated at</dt><dd className="plain">{T.generatedAt}</dd>
              <dt>Source</dt><dd><a href={T.githubUrl} target="_blank" rel="noopener noreferrer">{T.githubUrl.replace(/^https?:\/\//, "")}</a></dd>
            </dl>
          </section>

          <section className="about-sec">
            <h4>Mission</h4>
            <p className="about-mission">{T.mission}</p>

            <h4>Agent Roster</h4>
            <ul className="about-roster">
              {D.roster.map((a) => (
                <li key={a.name}>
                  <span className="ic" aria-hidden="true">{a.icon}</span>
                  <span className="rt">
                    <span className="rn">{a.name}</span>
                    <span className="rr">{a.role}</span>
                  </span>
                </li>
              ))}
            </ul>
          </section>
        </div>

        <div className="about-foot">
          <span>{T.author}</span>
          <span>{dash === "plan" ? "Plan-Status" : "Pipeline"} · {P.release}</span>
        </div>
      </div>
    </div>
  );
}

function Chrome({ dash, setDash, theme, setTheme, onAbout }) {
  return (
    <div className="chrome">
      <div className="brand"><span className="dot" /><span>Plan Visualizer</span></div>
      <div className="segs" role="tablist" aria-label="Dashboard">
        <button aria-pressed={dash === "plan"} onClick={() => setDash("plan")}>Plan-Status</button>
        <button aria-pressed={dash === "live"} onClick={() => setDash("live")}>Pipeline</button>
      </div>
      <div className="spacer" />
      <span className={`mode-badge ${dash === "plan" ? "mode-report" : "mode-live"}`}>
        <span className="pip" />
        {dash === "plan" ? "REPORT" : "LIVE"}
      </span>
      <button className="iconbtn" onClick={onAbout} aria-label="About">
        <span className="i">ⓘ</span> About
      </button>
      <div className="theme" role="tablist" aria-label="Theme">
        <button aria-pressed={theme === "light"} onClick={() => setTheme("light")}>☀ Light</button>
        <button aria-pressed={theme === "dark"}  onClick={() => setTheme("dark")}>☾ Dark</button>
      </div>
    </div>
  );
}

function App() {
  const [dash, setDash]   = useState(() => localStorage.getItem("pv-dash")  || "plan");
  const [theme, setTheme] = useState(() => localStorage.getItem("pv-theme") || "light");
  const [aboutOpen, setAboutOpen] = useState(false);

  useEffect(() => { document.documentElement.setAttribute("data-theme", theme); localStorage.setItem("pv-theme", theme); }, [theme]);
  useEffect(() => { localStorage.setItem("pv-dash", dash); }, [dash]);

  const openAbout = useCallback(() => setAboutOpen(true), []);
  const closeAbout = useCallback(() => setAboutOpen(false), []);

  return (
    <div className={`app ${dash === "live" ? "is-live" : ""}`} data-screen-label={dash === "plan" ? "Plan-Status" : "Pipeline"}>
      <Chrome dash={dash} setDash={setDash} theme={theme} setTheme={setTheme} onAbout={openAbout} />
      {dash === "plan" ? <window.PlanDashboard theme={theme} /> : <window.LiveDashboard />}
      {aboutOpen && <AboutModal dash={dash} onClose={closeAbout} />}
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
