'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const { renderIndex, compactMemory, readEntries } = require('../../tools/lib/memory-index');

describe('renderIndex', () => {
  test('groups by category, sorts sessions/snapshots desc, topics alpha', () => {
    const entries = [
      { category: 'topics', title: 'Technology', file: 'docs/memory/topics/technology.md', date: '2026-04-22' },
      {
        category: 'topics',
        title: 'Project Identity',
        file: 'docs/memory/topics/project-identity.md',
        date: '2026-03-09',
      },
      {
        category: 'sessions',
        title: 'GitHub Status Monitoring',
        file: 'docs/memory/sessions/2026-05-08-github-status-monitoring.md',
        date: '2026-05-08',
      },
      {
        category: 'sessions',
        title: 'Plugin Install',
        file: 'docs/memory/sessions/2026-05-10-plugin-install.md',
        date: '2026-05-10',
      },
      {
        category: 'snapshots',
        title: 'Project Completion Status',
        file: 'docs/memory/snapshots/2026-05-05-project-completion-status.md',
        date: '2026-05-05',
      },
    ];
    const out = renderIndex(entries);
    expect(out).toContain('<!-- generated by tools/memory.js — do not edit by hand -->');
    expect(out).toContain('# MEMORY.md');
    expect(out).toContain('## Topics');
    expect(out).toContain('## Sessions');
    expect(out).toContain('## Snapshots');
    expect(out).toContain('[Project Identity](docs/memory/topics/project-identity.md) · 2026-03-09');
    expect(out.indexOf('Plugin Install')).toBeLessThan(out.indexOf('GitHub Status'));
    expect(out.indexOf('Project Identity')).toBeLessThan(out.indexOf('Technology'));
  });

  test('omits empty category sections', () => {
    const entries = [
      { category: 'topics', title: 'Only One', file: 'docs/memory/topics/only-one.md', date: '2026-05-10' },
    ];
    const out = renderIndex(entries);
    expect(out).toContain('## Topics');
    expect(out).not.toContain('## Sessions');
    expect(out).not.toContain('## Snapshots');
  });

  test('handles empty entries', () => {
    const out = renderIndex([]);
    expect(out).toContain('<!-- generated');
    expect(out).not.toContain('## Topics');
  });
});

describe('compactMemory and readEntries (filesystem)', () => {
  let tmpdir;
  beforeEach(() => {
    tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'memidx-'));
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/topics'), { recursive: true });
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/sessions'), { recursive: true });
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/snapshots'), { recursive: true });
  });
  afterEach(() => fs.rmSync(tmpdir, { recursive: true, force: true }));

  test('readEntries reads H1 titles from files', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/foo.md'), '# Foo Topic\n\nbody\n');
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/sessions/2026-05-10-bar.md'), '# Bar Session\n\nbody\n');
    const entries = readEntries(tmpdir);
    expect(entries).toHaveLength(2);
    const foo = entries.find((e) => e.category === 'topics');
    expect(foo.title).toBe('Foo Topic');
    expect(foo.file).toBe('docs/memory/topics/foo.md');
  });

  test('compactMemory writes MEMORY.md with content from topic files', () => {
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/x.md'), '# X Topic\n\nbody\n');
    compactMemory({ root: tmpdir });
    const content = fs.readFileSync(path.join(tmpdir, 'MEMORY.md'), 'utf8');
    expect(content).toContain('# MEMORY.md');
    expect(content).toContain('[X Topic]');
  });

  test('compactMemory is no-op when docs/memory/ missing', () => {
    const tmp2 = fs.mkdtempSync(path.join(os.tmpdir(), 'memidx-noop-'));
    expect(() => compactMemory({ root: tmp2 })).not.toThrow();
    expect(fs.existsSync(path.join(tmp2, 'MEMORY.md'))).toBe(false);
    fs.rmSync(tmp2, { recursive: true, force: true });
  });

  test('compactMemory skips files in archive/', () => {
    fs.mkdirSync(path.join(tmpdir, 'docs/memory/archive/topics'), { recursive: true });
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/archive/topics/old.md'), '# Old\n\nbody\n');
    fs.writeFileSync(path.join(tmpdir, 'docs/memory/topics/new.md'), '# New\n\nbody\n');
    compactMemory({ root: tmpdir });
    const content = fs.readFileSync(path.join(tmpdir, 'MEMORY.md'), 'utf8');
    expect(content).toContain('[New]');
    expect(content).not.toContain('[Old]');
  });
});
